// <auto-generated />
namespace PlantDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class plantwater : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(plantwater));
        
        string IMigrationMetadata.Id
        {
            get { return "202206012000402_plant-water"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
